# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

common: &common
  secret_key_base: 5379e2767ff792abb8367b647eb5897b5ab62f1bd0c7c5f3f4cc636392472ded70c6e603362ab1d729a97527d8b1ba6e7ec16042a79e6073ff56da01a0d3e057

  door_code: "<%= ENV["DOOR_CODE"] || '0000' %>"
  wifi_password: "makestuff"

  stripe_publishable_key: <%= ENV["STRIPE_PUBLISHABLE_KEY"] || 'pk_test_9roddYi1U4CrBxrQUIRmFCSl' %>
  stripe_secret_key: <%= ENV["STRIPE_SECRET_KEY"] || 'sk_test_Jx36AA1fL6yLxbmK8IGuGKHj' %>

  vending_machine_token: <%= ENV["TOKEN_VENDING_MACHINE"] || '5047bfe23e3490bfaea4bbf07f2e60' %>
  doorbot_members_token: <%= ENV["TOKEN_DOORBOT_MEMBERS"] || '03ddab605e31b98dc013797c6ab93e5d' %>

  facebook_app_key: <%= ENV["FACEBOOK_APP_KEY"] || '374797396038083' %>
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] || '774047656817a921636ad2a4e659f9e2' %>

test:
  <<: *common

development:
  <<: *common

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *common

  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

  vending_machine_token: <%= ENV["VENDING_MACHINE_TOKEN"] %>
